require("plugins.colorscheme")
-- require("plugins.copilot")
require("plugins.gitsigns")
require("plugins.guess-indent")
require("plugins.harpoon")
require("plugins.lspconfig")
require("plugins.mini")
require("plugins.neo-tree")
require("plugins.oil")
require("plugins.scrollbar")
require("plugins.telescope")
require("plugins.todo-comments")
require("plugins.treesitter")
require("plugins.treesitter-context")
require("plugins.undotree")
require("plugins.which-key")
